import os
import socket
import urllib.parse
from pathlib import Path

ROOT_DIR = Path(__file__).parent.resolve()
BACKEND_ENV = ROOT_DIR / "backend" / ".env"
FRONTEND_ENV = ROOT_DIR / "frontend" / ".env"

def check_local_port(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0

def configure_environment():
    print("==================================================")
    print(" AnomIQ Full-Stack Environment Generator")
    print("==================================================")

    # 1. Supabase Input
    print("\n--- [1/3] Supabase Configuration ---")
    project_ref = input("Enter Supabase Project Ref (e.g., abcdefghijklm): ").strip()
    db_password = input("Enter Supabase Database Password: ").strip()
    encoded_password = urllib.parse.quote_plus(db_password)
    
    region = input("Enter AWS Region (default: ap-south-1): ").strip() or "ap-south-1"
    database_url = f"postgresql://postgres.{project_ref}:{encoded_password}@aws-0-{region}.pooler.supabase.com:6543/postgres"

    # 2. Google Gemini Input
    print("\n--- [2/3] Google Gemini AI Studio ---")
    gemini_key = input("Enter your GEMINI_API_KEY (starts with AIzaSy...): ").strip()

    # 3. Render / Backend Domain Input
    print("\n--- [3/3] Hosting & Endpoints ---")
    render_slug = input("Enter Render service name (leave blank if not yet created): ").strip()
    if render_slug:
        render_url = f"https://{render_slug}.onrender.com"
    else:
        render_url = "http://localhost:8000"

    # Write backend/.env
    BACKEND_ENV.parent.mkdir(parents=True, exist_ok=True)
    backend_content = f"""# Auto-generated by setup_env.py
DATABASE_URL="{database_url}"
GEMINI_API_KEY="{gemini_key}"
CORS_ORIGINS="http://localhost:5173,http://127.0.0.1:5173,https://*.vercel.app"
PORT=8000
"""
    BACKEND_ENV.write_text(backend_content, encoding="utf-8")
    print(f"\n[OK] Wrote backend configuration to: {BACKEND_ENV}")

    # Write frontend/.env
    FRONTEND_ENV.parent.mkdir(parents=True, exist_ok=True)
    frontend_content = f"""# Auto-generated by setup_env.py
VITE_API_URL="http://localhost:8000"
# Production Render URL for Vercel deployment:
# VITE_API_URL="{render_url}"
"""
    FRONTEND_ENV.write_text(frontend_content, encoding="utf-8")
    print(f"[OK] Wrote frontend configuration to: {FRONTEND_ENV}")

    # Connectivity Diagnostics
    print("\n--- Running Diagnostics ---")
    try:
        from google import genai
        client = genai.Client(api_key=gemini_key)
        res = client.models.generate_content(model="gemini-2.5-flash", contents="Ping")
        print("[SUCCESS] Gemini API key verified and responsive.")
    except Exception as e:
        print(f"[WARNING] Gemini validation check failed: {e}")

    try:
        import psycopg2
        conn = psycopg2.connect(database_url, connect_timeout=5)
        conn.close()
        print("[SUCCESS] Supabase transaction pooler connected successfully.")
    except Exception as e:
        print(f"[WARNING] Supabase database connection failed: {e}")

    print("\nLocal Environment Setup Complete.")

if __name__ == "__main__":
    configure_environment()